apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dvoq8xj6w-python
  janus-idp.io/tekton: dvoq8xj6w-python
  backstage.io/kubernetes-id: dvoq8xj6w-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dvoq8xj6w-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
