apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dvoq8xj6w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dvoq8xj6w-python 
  name: dvoq8xj6w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dvoq8xj6w-python 
